repo_id,repo_full_name,file,file_sha1,match
373684696,daedalus/CVE-2021-21985,exploit.py,020ecc5894eaada2d16d3788832e947a886413d6,CVE-2021-21985
373684696,daedalus/CVE-2021-21985,_GITHUB_REPO_METADATA_,,CVE-2021-21985
