repo_id,repo_full_name,file,file_sha1,match
66629029,ankh2054/python-exploits,ms08_067.py,00be85c3a0816273af9ee3f8004b3c172a42a010,MS08-067
66629029,ankh2054/python-exploits,ms09-050.py,0aca7abbe0acd5af6e0345edb077a56b02f6e089,MS09-050
66629029,ankh2054/python-exploits,ie_aurora.py,1c15ce022c8d6be33ce1ce6a747923d4e9ad3ff7,CVE-2010-0249
66629029,ankh2054/python-exploits,README.md,84dc5ab6029461644d2ae54250fbe56907437ea5,CVE-2003-0727
66629029,ankh2054/python-exploits,README.md,84dc5ab6029461644d2ae54250fbe56907437ea5,CVE-2009-3103
66629029,ankh2054/python-exploits,README.md,84dc5ab6029461644d2ae54250fbe56907437ea5,CVE-2010-0249
66629029,ankh2054/python-exploits,README.md,84dc5ab6029461644d2ae54250fbe56907437ea5,CVE-2010-4221
66629029,ankh2054/python-exploits,README.md,84dc5ab6029461644d2ae54250fbe56907437ea5,MS08-067
66629029,ankh2054/python-exploits,README.md,84dc5ab6029461644d2ae54250fbe56907437ea5,MS09-050
