repo_id,repo_full_name,file,file_sha1,match
257074392,Fa1c0n35/vmware_vcenter_cve_2020_3952,exploit.py,3074f3f42bafeded36b2f5e103051dc4ba340918,CVE-2020-3952
257074392,Fa1c0n35/vmware_vcenter_cve_2020_3952,README.md,ed91593d0d7605a4a80c42051544060d3c2ccaf0,CVE-2020-3952
257074392,Fa1c0n35/vmware_vcenter_cve_2020_3952,_GITHUB_REPO_METADATA_,,CVE-2020-3952
