repo_id,repo_full_name,file,file_sha1,match
401984571,Udyz/CVE-2021-26084,confluence-rce.py,3aea1aa0046ab6de1f51b135910304dae29886fb,CVE-2021-26084
401984571,Udyz/CVE-2021-26084,README.md,716cc3690670e03edb1f8ff863c15b9fd60d0f3a,CVE-2021-26084
401984571,Udyz/CVE-2021-26084,_GITHUB_REPO_METADATA_,,CVE-2021-26084
